#!/bin/sh

# ensure only one instance of this script is running
pids=$(pidof -wx $0)
for pid in $pids; do
    if [ $pid != $$ ]; then
        kill -9 $pid
    fi
done

PARAM=(
    --lock
    --display 1
    --
    {%@@ if profile == "eta" @@%}
    --radius=40
    --ind-pos="x+370:y+h-95"
    --time-pos="ix-325:iy+0"
    --time-size=50
    --date-pos="ix-325:iy+35"
    --date-size=24
    {%@@ elif profile == "pi" @@%}
    --radius=35
    --ind-pos="x+310:y+h-80"
    --time-pos="ix-265:iy+0"
    --time-size=40
    --date-pos="ix-265:iy+35"
    --date-size=20
    {%@@ endif @@%}
    --date-align 1
    --date-str="%A, %d.%m.%Y"
    --date-color=ffffffff
    --date-font="sans-serif"
    --layout-pos="ix-1000:iy+1000"
    --no-modkey-text
    --greeter-text=""
    --verif-text=""
    --wrong-text=""
    --ignore-empty-password
    --nofork
)

function restart_services {
    {%@@ if profile == "eta" @@%}
    ~/.scripts/streamdeck restart
    {%@@ elif profile == "pi" @@%}
    :
    {%@@ endif @@%}
}

if [ $(pidof -ws "mpd") > /dev/null ] || [ $(pidof -ws "mopidy") > /dev/null ]; then
    mpc pause > /dev/null
fi

(betterlockscreen "${PARAM[@]}"; restart_services; kill -9 $$) > /dev/null &

if [ -z $1 ]; then
	time=300
else
	time=$1
fi

sleep $time; pidof -ws i3lock && systemctl suspend

