#!/bin/sh

{%@@ if profile == "eta" @@%}
icon='/home/moritz/.config/i3/icons/icon2.png'
{%@@ elif profile == "pi" @@%}
icon='/home/moritz/.config/i3/icons/icon.png'
{%@@ endif @@%}
tmpbg='/tmp/i3lock.png'

scrot -z "$tmpbg"

convert "$tmpbg" -brightness-contrast -20x-20 -blur "0x5" "$icon" -gravity center -composite -matte "$tmpbg"

# Pause mpd-Playback
if [ $(pidof -ws "mpd") > /dev/null ] || [ $(pidof -ws "mopidy") > /dev/null ];
then
	mpc pause
fi

i3lock -u -t -i $tmpbg

if [ -z "$1" ];
then
	time=300;
else
	time="$1";
fi

sleep "$time"; pidof -ws i3lock && systemctl suspend

rm $tmpbg
