#!/bin/sh

if [ $(pidof -ws "mpd") > /dev/null ] || [ $(pidof -ws "mopidy") > /dev/null ];
then

    if [ "$1" == "toggleplay" ];
    then
        mpc -q toggle
    elif [ -z "$(mpc current)" ];
    then
        echo ""
    else
        file=$(mpc --format %file% | head -n 1)
        name=$(mpc --format %name% | head -n 1)

        if [[ "$file" == *"http"* ]];
        then
            title="$name"
        else
            title=$(mpc --format %title% | head -n 1 | cut -f1 -d"(" | cut -f1 -d"-")
            artist=$(mpc --format %artist% | head -n 1 | cut -f1 -d";")
            title="${title%% } - $artist"
        fi

        echo "$title"
    fi
else
    echo ""
fi
