#!/bin/sh

if pidof "mpd" > /dev/null
then
    case "$1" in
        "playpause") mpc toggle ;;
        "stop")      mpc stop ;;
        "next")      mpc next ;;
        "prev")      mpc prev ;;
    esac
fi
