#!/bin/sh
#
if [ $(pidof -ws "spotifyd") 2> /dev/null ]; then
    case "$1" in
        "toggle")    spt pb --toggle;;
        "next")      spt pb --next ;;
        "prev")      spt pb --previous ;;
        "shuffle")   spt pb --shuffle ;;
        "forward")   spt pb --seek +10 ;;
        "backward")  spt pb --seek -10 ;;
        "vol_up")    spt pb --volume 80 ;;
        "vol_down")  spt pb --volume 70 ;;
        "current")
            title=$(spt pb -s -f '%t' 2> /dev/null | cut -f1 -d"(" | cut -f1 -d"-")
            artist=$(spt pb -s -f '%a' 2> /dev/null | cut -f1 -d",")
            if [[ "$title" != "" ]]; then
                title="${title} - ${artist}"
            fi
            echo $title
            ;;
    esac
elif [ $(pidof -ws "mpd") 2> /dev/null ]; then
    case "$1" in
        "toggle")    mpc toggle ;;
        "stop")      mpc stop ;;
        "next")      mpc next ;;
        "prev")      mpc prev ;;
        "shuffle")   mpc random ;;
        "forward")   mpc seek +00:00:10 ;;
        "backward")  mpc seek -00:00:10 ;;
        "vol_up")    mpc volume +5 ;;
        "vol_down")  mpc volume -5 ;;
        "current")
            file=$(mpc -q --format %file% 2> /dev/null)

            if [[ "$file" == "" ]]; then
                title=""
            elif [[ "$file" == *"http"* ]]; then
                title=$(mpc -q --format %name% 2> /dev/null)
            else
                title=$(mpc -q --format %title% 2> /dev/null | cut -f1 -d"(" | cut -f1 -d"-")
                artist=$(mpc -q --format %artist% 2> /dev/null | cut -f1 -d";")
                title="${title%% } - $artist"
            fi
            echo "$title"
            ;;
    esac
else 
    case "$1" in
        "current") echo "" ;;
    esac
fi

