#!/bin/sh

case $1 in
    "s"|"shutdown"|"poweroff")
        ssh -t "moritz@delta" "sudo poweroff"
        ;;
    "r"|"reboot")
        ssh -t "moritz@delta" "sudo reboot"
        ;;
    *)
        ssh "moritz@delta"
        ;;
esac
