#!/bin/sh

case $1 in
    "s"|"shutdown"|"poweroff")
        ssh -t "moritz@xi" -o ConnectTimeout=2 -o ConnectionAttempts=2 "sudo shutdown"
        ;;
    "r"|"reboot")
        ssh -t "moritz@xi" "sudo reboot"
        ;;
    *)
        ssh "moritz@xi"
        ;;
esac

