#!/bin/sh

{%@@ if profile == "eta" @@%}
zenity --question --icon-name='gnome-shutdown' --width="370" --height=20 --title "System Shutdown" --timeout=5 --text "You pressed the system shutdown shortcut. \nDo you want to proceed?" \ && (streamdeck c; nas shutdown; shutdown 0)
{%@@ elif profile == "pi" @@%}
zenity --question --icon-name='gnome-shutdown' --width="370" --height=20 --title "System Shutdown" --timeout=5 --text "You pressed the system shutdown shortcut. \nDo you want to proceed?" \ && shutdown 0
{%@@ endif @@%}

