#!/bin/sh

DECKMASTER="${HOME}/Public/deckmaster/deckmaster"
DECKMASTER_CONFIG="${HOME}/.config/streamdeck/main.deck"

case $1 in
    "s"|"S"|"start")
        i3-msg exec "$DECKMASTER -deck $DECKMASTER_CONFIG"
        ;;
    "r"|"R"|"restart")
        killall deckmaster -q
        i3-msg exec "$DECKMASTER -deck $DECKMASTER_CONFIG"
        ;;
    "c"|"C"|"clear")
        killall deckmaster -q
        i3-msg exec "$DECKMASTER -deck $DECKMASTER_CONFIG -brightness 0"
        sleep 1
        killall deckmaster -q
        ;;
    *)
        ;;
esac

