#!/bin/sh

[ -z $1 ] && exit

if xdotool search --classname "$1"; then
    if xdotool search --onlyvisible --classname "$1"; then
        i3-msg "[instance=$1] move scratchpad;"
    else
        i3-msg "[instance=$1] scratchpad show;"
    fi
    exit
fi

NORMAL_DIMS="-o window.dimensions.lines=40 -o window.dimensions.columns=120"
BIG_DIMS="-o window.dimensions.lines=50 -o window.dimensions.columns=140"
WEATHER_DIMS="-o window.dimensions.lines=38 -o window.dimensions.columns=125"
case $1 in
    "TODO") i3-msg exec "alacritty --class $1 $NORMAL_DIMS -e nvim +':Note TODO'" ;;
    "MUSIC")
        pidof -ws spotifyd && player="spt" || player="ncmpcpp"
        i3-msg exec "alacritty --class $1 $NORMAL_DIMS -e $player" ;;
    "CALENDAR") i3-msg exec "alacritty --class $1 $NORMAL_DIMS -e calcurse" ;;
    "WTTR") i3-msg exec "alacritty --class $1 $WEATHER_DIMS -e weather_update" ;;
    "SYSINFO") i3-msg exec "alacritty --class $1 $BIG_DIMS -e btop" ;;
    *) ;;
esac

