#!/bin/sh

{%@@ if profile == "eta" @@%}
apps=(st chromium thunderbird nemo telegram-desktop)
{%@@ elif profile == "pi" @@%}
apps=(st)
{%@@ endif @@%}

for ws in "${!apps[@]}"
do
    if (( $ws > 0 )); then
        i3-msg "workspace $((ws + 1))"
    fi
    i3-msg "append_layout /home/moritz/.config/i3/workspace-$((ws + 1)).json"
    i3-msg "exec --no-startup-id ${apps[${ws}]}"
done

if (( ${#apps[@]} > 1 )); then
    i3-msg "workspace 1"
fi

