#!/bin/sh

{%@@ if profile == "eta" @@%}
apps=(st brave thunderbird nemo telegram-desktop)
{%@@ elif profile == "pi" @@%}
apps=(st)
{%@@ endif @@%}

for ws in "${!apps[@]}"
do
    if [[ $((ws)) -ne 0 ]]; then
        i3-msg "workspace $((ws + 1))"
    fi
    i3-msg "append_layout /home/moritz/.config/i3/workspace-$((ws + 1)).json"
    i3-msg "exec --no-startup-id ${apps[$ws]}"
done

i3-msg "workspace 1"
